version: '3.6'

services:
  tvheadend:
    image: linuxserver/tvheadend
    container_name: tvheadend
    environment:
      - PUID=${TV_ID}
      - PGID=${TV_GUID}
      - TZ=${TIME_ZONE}
      - UMASK_SET=022
      #- RUN_OPTS=<run options here> #optional
    volumes:
      - config_tvheadend:/config
      - ${REC_DIR}:/recordings
    ports:
      - 9981:9981
      - 9982:9982
    devices:
      - /dev/dri:/dev/dri
      - /dev/dvb:/dev/dvb
    restart: unless-stopped
    depends_on:
      - comcutter
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    volumes:
      - config_sabnzbd:/config
      - ${INCOMP_DIR}:/incomplete-downloads
      - ${COMP_DIR}:/downloads
    ports:
      - "8080:8080"
      - "9095:9095"
    restart: always
    environment:
      - PUID=${SAB_ID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      # This will ensure files have the sabnzbd user, and media group when moved to your
      # media storage director(y|ies)
      - UMASK_SET=022
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - sabnzbd
    volumes:
      - config_sonarr:/config
      #- plex_tv:/tv
      - ${TV_DIR}:/tv
      - "/etc/localtime:/etc/localtime:ro"
      - ${COMP_DIR}:/downloads
    ports:
      - "8989:8989"
      - "9898:9898"
    links:
      - sabnzbd
    restart: always
    environment:
      - PUID=${SON_ID}
      - PGID=${PGID}
      - UMASK_SET=022
      - TZ=${TIME_ZONE}
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      - sabnzbd
    environment:
      - PUID=${RAD_ID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    volumes:
      - config_radarr:/config
      - ${MOVIES_DIR}:/movies
      - ${COMP_DIR}:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  comcutter:
    image: bljohnsondev/comcutter
    container_name: comcutter
    environment:
      - PUID=${CMSKP_ID}
      - PGID=${TV_GUID}
      - TZ=${TIME_ZONE}
    ports:
      - 9090:9090
    volumes:
      - config_comskip:/data
      - ${REC_DIR}:/library
    restart: unless-stopped

volumes:
  config_sabnzbd:
    driver: local
    driver_opts:
      type: none
      device: $PWD/configs/sabnzbd/
      o: bind
  config_tvheadend:
    driver: local
    driver_opts:
      type: none
      device: $PWD/configs/tvheadend/
      o: bind
  config_sonarr:
    driver: local
    driver_opts:
      type: none
      device: $PWD/configs/sonarr/
      o: bind
  config_radarr:
    driver: local
    driver_opts:
      type: none
      device: $PWD/configs/radarr/
      o: bind
  config_comskip:
    driver: local
    driver_opts:
      type: none
      device: $PWD/configs/comskip/
      o: bind

  downloads:
  downloads_incomplete:














